# Generated by Django 2.2.7 on 2019-11-14 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_boarsd_created_by'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Boarsd',
            new_name='Board',
        ),
    ]
